### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by TrinhTuanHung2021** [guidytz/SUMO-QL#7]
Hello
Thank you very much for sharing your model and paper. It's worth it to me.

I would like to ask you a question. In your model, you used Q learning with a road network. You defined state space as `Nodes`  and actions as `the outgoing edges. 
So is there any difference if you used signalized intersections instead of unsignalized intersections?
You used Q Learning. I hope that you will upgrade to DQN in the next paper.

**Comment by guidytz** [comment]
Hello,
I'm glad our work helps you in some way!

When you say signalized intersections, you mean intersections with traffic lights?
If so, we have not tested our work extensively in networks that have traffic lights, but I believe that they shouldn't impose a significant change in the learning performance.

As for the extensions to our work, we have implemented a Pareto Q Learning method with the idea to optimize more than one objective (eg. reduce travel time and pollutants emission in specific areas). The code is unstable and not well documented yet, but there are plans on fixing most issues soon.

We currently have no plans on upgrading to DQN in the moment, but it might be a good add-on in the future.

**Comment by TrinhTuanHung2021** [comment]
Thank you very much
